# Generated by Django 3.2 on 2021-04-19 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        ('instructions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('ingredients', models.ManyToManyField(related_name='potions', to='ingredients.Ingredient')),
                ('instructions', models.ManyToManyField(related_name='potions', to='instructions.Instruction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
