# Generated by Django 3.2 on 2021-04-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('potions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='ingredients',
            field=models.ManyToManyField(related_name='potions', to='ingredients.Ingredient'),
        ),
    ]
